blog/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings


app_name = "blog"

urlpatterns = [
    path('', index, name='index'),
    path('courses/', courses_list, name='courses_list'),
    path('courses/<str:slug>', courses_detail, name='courses_detail'),
    path('post/<str:slug>', post_detail, name='post_detail')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

childs/urls.py
from django.urls import path
from .views import *

app_name = 'childs'

urlpatterns = [
    path('courses_list/', courses_list, name='coursess_list'),
    path('child_list/<str:slug>', childs_list, name='child_list')
]

contacts/urls.py
from django.urls import path
from .views import *

app_name = 'contacts'

urlpatterns = [
    path('contacts', contacts_list, name='contacts_list')
]

courses/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('childs.urls')),
    path('', include('contacts.urls'))
]

blog/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.
from time import time


def upload_location(instance, filename):
    return "%s/%s" % (instance.id, filename)


def gen_slug(s):
    new_slug = slugify(s, allow_unicode=True)
    return new_slug + "-" + str(int(time()))


class Post(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название поста')
    slug = models.SlugField(max_length=50, unique=True, blank=True)
    image = models.ImageField(verbose_name='Фото продукта', height_field="height_field",
                              width_field="width_field", upload_to=upload_location)
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    link = models.CharField(max_length=300, verbose_name='Ссылка на видео')
    published_date = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')
    homework = models.TextField(verbose_name='Домашнее задание')
    views = models.IntegerField('Просмотры', default=0)
    course = models.ForeignKey('Course', related_name='posts', on_delete=models.CASCADE)

    def get_absolute_url(self):
        return "post/%s" % self.slug

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = gen_slug(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Урок'
        verbose_name_plural = 'Уроки'
        ordering = ['-published_date']


class Course(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название курса')
    slug = models.SlugField(max_length=50, unique=True, blank=True)

    def get_absolute_url(self):
        return "course/%s" % self.slug

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = gen_slug(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

childs/models.py
from django.db import models
from blog.models import Course
# Create your models here.
from django.utils.text import slugify
from time import time


def gen_slug(s):
    new_slug = slugify(s, allow_unicode=True)
    return new_slug + "-" + str(int(time()))


class Child(models.Model):
    name = models.CharField(max_length=40, verbose_name='Имя ученика', db_index=True)
    slug = models.SlugField(max_length=50, unique=True, blank=True)
    paid = models.BooleanField(default=False)
    homework = models.BooleanField(default=False)
    course = models.ForeignKey(Course, related_name='childs', on_delete=models.PROTECT)


    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = gen_slug(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Ученики'
        verbose_name = "Ученик"
        ordering = ['pk']

contacts/models.py
from django.db import models

# Create your models here.


class Teacher(models.Model):
    name = models.CharField(max_length=50, verbose_name='Имя преподавателя', db_index=True)
    phone = models.CharField(max_length=50, verbose_name='Номер')
    telegram = models.CharField(max_length=50, verbose_name='Телеграм')
    email = models.EmailField(max_length=50, verbose_name='Эмайл')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Учитель'
        verbose_name_plural = 'Учителя'
        ordering = ['name']

blog/views.py
from django.shortcuts import render
from .models import *
from django.db.models import Q
from django.core.paginator import Paginator
# Create your views here.


def index(request):
    return render(request, 'blog/index.html')


def courses_list(request):
    courses = Course.objects.all()
    return render(request, 'blog/courses.html', {'courses': courses})


def courses_detail(request, slug):
    course = Course.objects.get(slug__iexact=slug)
    # search_query = request.GET.get('search', '')
    # if search_query:
    #     posts = course.posts.filter(Q(title__contains=search_query) | Q(content__icontains=search_query))
    #
    # else:
    #     posts = course.posts.all()
    posts = course.posts.all()
    paginator = Paginator(posts, 4)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)
    is_paginated = page.has_other_pages()
    if page.has_previous():
        prev_url = '?page={}'.format(page.previous_page_number())

    else:
        prev_url = ''

    if page.has_next():
        last_url = '?page={}'.format(paginator.page_range[-1])
        next_url = '?page={}'.format(page.next_page_number())

    else:
        next_url = ''
        last_url = ''
    return render(request, 'blog/course_detail.html', {'course': course, 'posts': posts, 'is_paginated': is_paginated,
                                                       'page_object': page, 'prev_url': prev_url, 'next_url': next_url,
                                                       'last_url': last_url})


def post_detail(request, slug):
    post = Post.objects.get(slug__iexact=slug)
    post.views += 1
    post.save(update_fields=['views'])
    return render(request, 'blog/post_detail.html', {'post': post})

childs/views.py
from django.shortcuts import render
from .models import *
from blog.models import Course
# Create your views here.


def courses_list(request):
    courses = Course.objects.all()
    return render(request, 'childs/courses.html', {'course': courses})


def childs_list(request, slug):
    course = Course.objects.get(slug__iexact=slug)
    childs = course.childs.all()
    return render(request, 'childs/childs_list.html', {'childs': childs})

contacts/views.py
from django.shortcuts import render
from .models import *
# Create your views here.


def contacts_list(request):
    teachers = Teacher.objects.all()
    return render(request, 'contacts/contacts_list.html', {'teachers': teachers})

blog/templates/blog/course_detail.html
{% extends 'base.html' %}

{% block style %}
    <style>
    .col-md-12{
        margin-left: 40%;
    }
    </style>
{% endblock %}

{% block content %}
    <h1 align="center">{{ course }}</h1>
    <div class="row">
            <div class="col-md-12 offset-4">
                {% for post in page_object.object_list %}
                    <div class="card" style="width: 18rem;">
                    {% if post.image %}
                        <img src="{{ post.image.url }}" class="card-img-top" alt="">
                    {% endif %}

                      <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text" style="height: 100px; overflow-y: hidden">{{ post.content }}</p>
                        <a href="{% url 'blog:post_detail' slug=post.slug %}" class="btn btn-primary">Перейти к уроку</a>
                      </div>
                    </div>
                {% endfor %}


        </div>
    </div>
<nav aria-label="Page navigation example" class="mt-5">
  <ul class="pagination justify-content-center">

    <li class="page-item {% if not prev_url %}disabled{% endif %}">
      <a class="page-link" href="{{ prev_url }}" tabindex="-1" aria-disabled="true">Previous</a>
    </li>
      {% for n in page_object.paginator.page_range %}
      {% if page_object.number == n %}
         <li class="page-item active"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
      {% elif n > page_object.number|add:-3 and n < page_object.number|add:3 %}
               <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
       {% endif %}

      {% endfor %}

    <li class="page-item {% if not next_url %}disabled{% endif %}">
      <a class="page-link" href="{{ next_url }}">Next</a>
    </li>

  </ul>
</nav>
{% endblock %}

blog/templates/blog/courses.html
{% extends 'base.html' %}
{% block style %}
    <style>
    .content{
        height: 600px;
    }
    a{

        color: black;
    }
    </style>
{% endblock %}
{% block content %}
    <div class="row mt-5 content">
    <div class="col-md-12">
         {% for cours in courses %}
                <h1 align="center"><a href="{% url 'blog:courses_detail' slug=cours.slug %}">{{ cours.title }}</a></h1>
            {% endfor %}
    </div>
    </div>


{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block style %}
    <style>
    h1{
        margin-top: 40px;
        margin-bottom: 30px;
    }
    .info{
        margin-top: 20px;
        width: 400px;
        margin-left: 37%;
    }
    .info p{
        text-align: justify;
        font-weight: normal;
        font-size: 18px;
    }
    .parents{
        width: 400px;
        margin-left: 37%;
    }
    .parents p{
        text-align: justify;
        font-weight: normal;
        font-size: 18px;
    }
    .childs{
        width: 400px;
        margin-left: 37%;
    }
    .childs p{
        text-align: justify;
        font-weight: normal;
        font-size: 18px;
    }
    </style>
{% endblock %}
{% block content %}
    <h1 align="center">Информация</h1>
    <div class="info">
        <p>На этом сайте будут выкладываться уроки. Во вкладке "Курсы" вы можете выбрать свой и перейти к просмотру уроков
            Уроки будут выкладываться 2 раза в неделю, как и проходили занятия.
        </p>
    </div>
    <h1 align="center">Для учеников</h1>
    <div class="childs">
        <p>
            Домашнее задание можно скинуть в телеграм, вайбер, или на почту, все данные указаны во вкладке "контакты"
        </p>
    </div>
    <h1 align="center">Для родителей</h1>
    <div class="parents">
    <p>
        Во вкладке "ученики" будет список учеников, где каждый родитель сможет посмотреть на успеваемость своего ребёнка
    </p>
    </div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block style %}
    <style>
        .info img{
            width: 600px;
            height: 300px;
            margin-left: 60px;
        }
        .info p{
            width: 730px;
            text-align: justify;
        }
    .btn{
        position: fixed;
        top: 10%;
        left: 0%;

    }
    iframe{
        width:730px;
        height:400px;
    }
    h4{
        margin-left:300px;
        margin-bottom: 50px;
    }
    @media screen and (max-width: 420px){
        h4{
            margin-left: 20px;
        }
        .info img{
            width: 390px;
            height: 200px;
            margin-left: -100px;
        }
        iframe{
            margin-left: -100px;
            width: 390px;
            height: 200px;
        }
    }
    </style>
{% endblock %}

{% block content %}
    <h2 align="center">{{ post.title }}</h2>
    <div class="row info">
    <div class="col-md-12 offset-3">
         {% if post.image %}
        <img src="{{ post.image.url }}" alt="image">
    {% endif %}
    <h4>Конспект</h4>
    <p>{{ post.content }}</p>
    <h4>Видео урок</h4>
    <iframe src="{{ post.link }}"
            frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <p><small>Видеоурок</small></p>
    </div>
    </div>
    <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Домашнее задание
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <i class="fas fa-angry"></i><h5 class="modal-title" id="exampleModalLabel">Домашнее задание</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{ post.homework }}
      </div>

    </div>
  </div>
</div>

{% endblock %}

childs/templates/childs/childs_list.html
{% extends 'base.html' %}

{% block style %}
    <style>
    .table{
        margin-top: 100px;
        width: 800px;
        margin-left:25%;
        margin-bottom: 150px;
    }
    </style>
{% endblock %}

{% block content %}
<table class="table table-striped table-dark" >
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">ФИО</th>
      <th scope="col">Оплата за текущий месяц</th>
      <th scope="col">ДЗ за ткущую неделю</th>
    </tr>
  </thead>
  <tbody>
  {% for child in childs %}
    <tr>
      <th scope="row">{{ child.pk }}</th>
      <td>{{ child.name }}</td>
      <td>{{ child.paid }}</td>
      <td>{{ child.homework }}</td>
    </tr>
  {% endfor %}



  </tbody>
</table>
{% endblock %}

childs/templates/childs/courses.html
{% extends 'base.html' %}
{% block style %}
    <style>
    .content{
        height: 600px;
    }
    a{

        color: black;
    }
    </style>
{% endblock %}
{% block content %}
    <div class="row mt-5 content">
    <div class="col-md-12">

    {% for cours in course %}
        <h1 align="center"><a href="{% url 'childs:child_list' slug=cours.slug %}">{{ cours.title }}</a></h1>
    {% endfor %}


    </div>
    </div>


{% endblock %}

contacts/templates/contacts/contacts_list.html
{% extends 'base.html' %}

{% block style %}
    <style>
    .row{
        height: 600px;
    }
    </style>
{% endblock %}

{% block content %}
    <div class="row mt-5">
    <div class="col-md-12 offset-4">
        {% for teacher in teachers %}
            <h4>Учитель: <small style="font-size: 16px">{{ teacher.name }}</small></h4>
            <h4>Номер: <small style="font-size: 16px">{{ teacher.phone }}</small></h4>
            <h4>Телеграм: <small style="font-size: 16px">{{ teacher.telegram }}</small></h4>
            <h4>Почта: <small style="font-size: 16px">{{ teacher.email }}</small></h4>
        {% endfor %}


    </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Server Courses</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
 <style>

      html, body{
        overflow-x: hidden;
    }
        li{
            list-style: none;
        }
    </style>
    {% block style %}

    {% endblock %}

</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand ml-5" href="{% url 'blog:index' %}">Server</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link ml-5" href="{% url 'blog:courses_list' %}">Курсы</a>
      </li>
      <li class="nav-item">
        <a class="nav-link ml-5" href="{% url 'contacts:contacts_list' %}">Контакты</a>
      </li>
        <li class="nav-item">
        <a class="nav-link ml-5" href="{% url 'childs:coursess_list' %}">Ученики</a>
      </li>



    </ul>
{#    <form class="form-inline my-2 my-lg-0" action="{% url 'blog:courses_detail' slug=course.slug %}">#}
{#      <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">#}
{#      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
{#    </form>#}
  </div>
</nav>
{% block content %}

{% endblock %}


</body>
</html>